/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen3angelcapa.vista;

import conexion.Conexion;
import examen3angelcapa.Cuenta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Capa Brothers
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        setTitle("Registro Cuentas");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtNumCuenta = new javax.swing.JTextField();
        txtTipoCuenta = new javax.swing.JTextField();
        txtMovimiento = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        txtAnterior = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        txtSiguiente = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnPresentar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txtConsulta = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero Cuenta");

        jLabel2.setText("Cliente");

        jLabel3.setText("Tipo Cuenta");

        jLabel4.setText("Movimiento");

        jLabel5.setText("Fecha");

        jLabel6.setText("Saldo");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAnterior.setText("anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        txtSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiguienteActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnPresentar.setText("Presentar");
        btnPresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cuentas Bancarias");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(btnAnterior))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnSiguiente))
                                    .addComponent(txtNumCuenta)
                                    .addComponent(txtCliente)
                                    .addComponent(txtTipoCuenta)
                                    .addComponent(txtMovimiento)
                                    .addComponent(txtFecha)
                                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPresentar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregar)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSiguiente)
                    .addComponent(txtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnPresentar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Conexion con = new Conexion();
    Connection conexion = con.ControladorBadedeDatos();
    ArrayList<Cuenta> registro = new ArrayList<Cuenta>();
    PreparedStatement presentar;
    PreparedStatement buscarPorSaldo;
    int indiceActual = 0;
    int totalResultados = 0;
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String numCu = txtNumCuenta.getText();
        String client = txtCliente.getText();
        String tipCu = txtTipoCuenta.getText();
        String mov = txtMovimiento.getText();
        String fecha = txtFecha.getText();
        String saldo = txtSaldo.getText();

        try {
            PreparedStatement insertarRegistro = conexion.prepareStatement("INSERT INTO Registro (numeroCuenta,cliente,tipoCuenta,Movimiento,fecha,saldo) VALUES(?,?,?,?,?,?)");
            insertarRegistro.setString(1, numCu);
            insertarRegistro.setString(2, client);
            insertarRegistro.setString(3, tipCu);
            insertarRegistro.setString(4, mov);
            insertarRegistro.setString(5, fecha);
            insertarRegistro.setString(6, saldo);
            insertarRegistro.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos ingresados Correctamente", "Ingreso", JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException ex) {
            System.out.println("Agregar Persona " + ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        int count = indiceActual - 1;
        if (count >= 0) {
            Cuenta persona = registro.get(count);
            setTextos(persona, count, totalResultados);
            indiceActual = indiceActual - 1;
        } else {
            System.out.println("fin de la lista");
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void txtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiguienteActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtNumCuenta.setText("");
        txtCliente.setText("");
        txtTipoCuenta.setText("");
        txtMovimiento.setText("");
        txtFecha.setText("");
        txtSaldo.setText("");
        txtAnterior.setText("");
        txtSiguiente.setText("");
        txtConsulta.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed
        // TODO add your handling code here:
        presentar();
    }//GEN-LAST:event_btnPresentarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
        int count = indiceActual + 1;
        totalResultados = registro.size();
        if (count < totalResultados) {
            Cuenta cuenta = registro.get(count);
            setTextos(cuenta, count, totalResultados);
            indiceActual = indiceActual + 1;
        } else {
            System.out.println("fin de la lista");
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            String mod = "UPDATE Registro SET numeroCuenta='" + txtNumCuenta.getText()
                    + "',cliente='" + txtCliente.getText()
                    + "',tipoCuenta='" + txtTipoCuenta.getText()
                    + "',movimiento='" + txtMovimiento.getText()
                    + "',fecha='" + txtFecha.getText()
                    + "',saldo='" + txtSaldo.getText()
                    + "' WHERE numeroCuenta='" + txtConsulta.getText() + "'";
            PreparedStatement modificar = conexion.prepareStatement(mod);
            modificar.executeUpdate();
            System.out.println("Elementos modificados");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    ArrayList presentar() {
        try {
            String query = "Select * from Registro";
            presentar = conexion.prepareStatement(query);
            ResultSet resultado = presentar.executeQuery();
            while (resultado.next()) {
//                Libro libros = new Libro();
                String numeroCuenta = resultado.getString("numeroCuenta");
                String cliente = resultado.getString("cliente");
                String tipoCuenta = resultado.getString("tipoCuenta");
                String movimiento = resultado.getString("movimiento");
                String fecha = resultado.getString("fecha");
                String saldo = resultado.getString("Saldo");

                Cuenta libros = new Cuenta(numeroCuenta, cliente, tipoCuenta, movimiento, fecha, saldo);
                registro.add(libros);
            }
            for (int i = 0; i < registro.size(); i++) {
                System.out.println(registro.get(i).getCliente());
            }
            Cuenta c = registro.get(indiceActual);
            setTextos(c, indiceActual, registro.size());

//            conexion.close();
        } catch (SQLException ex) {
            System.out.println("Error al ejecutar la consulta" + ex);
        }
        return registro;
    }

    ArrayList getCUentasBalance() {
        ArrayList<Cuenta> cuentas = new ArrayList<Cuenta>();
        try {
            String query = "select *from Registro where saldo>" + 100 + "";
            buscarPorSaldo = conexion.prepareStatement(query);
            ResultSet resultado = buscarPorSaldo.executeQuery();
            while (resultado.next()) {
                Cuenta registro = new Cuenta();
                String numCu = resultado.getString("numeroCuenta");
                String client = resultado.getString("cliente");
                String tipCu = resultado.getString("tipoCuenta");
                String mov = resultado.getString("movimiento");
                String fecha = resultado.getString("fecha");
                String saldoo = resultado.getString("saldo");
                registro.setNumeroCuenta(numCu);
                registro.setCliente(client);
                registro.setTipo_Cuenta(tipCu);
                registro.setMovimiento(mov);
                registro.setFecha(fecha);
                registro.setSaldo(saldoo);
                cuentas.add(registro);

            }
            for (int i = 0; i < registro.size(); i++) {
                System.out.println(registro.get(i).getCliente());
            }
            Cuenta c = registro.get(indiceActual);
            setTextos(c, indiceActual, registro.size());

        } catch (SQLException ex) {
            System.out.println("Error al ejecutar la consulta" + ex);
        }
        return cuentas;
    }

    public void setTextos(Cuenta cuenta, int indiceActual, int totalResultados) {

        txtNumCuenta.setText(cuenta.getNumeroCuenta());
        txtCliente.setText(cuenta.getCliente());
        txtTipoCuenta.setText(cuenta.getTipo_Cuenta());
        txtMovimiento.setText(cuenta.getMovimiento());
        txtFecha.setText(cuenta.getFecha());
//        txtSaldo.setText(String.valueOf(cuenta.getSaldo()));
        txtSaldo.setText(cuenta.getSaldo());
        txtAnterior.setText(String.valueOf(indiceActual + 1));
        txtSiguiente.setText(String.valueOf(totalResultados));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPresentar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAnterior;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMovimiento;
    private javax.swing.JTextField txtNumCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtSiguiente;
    private javax.swing.JTextField txtTipoCuenta;
    // End of variables declaration//GEN-END:variables
}
